version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 543898
      MYSQL_DATABASE: dd
      MYSQL_USER: acp4pogynvaeidfj
      MYSQL_PASSWORD: jc31d2qyy7h9jv5jn1u9uosjksxzaizw
      MYSQL_TCP_PORT: 8514
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "8514:8514"
    networks:
      app-network:
        ipv4_address: 192.168.2.175
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prod-container
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - ./WebContent/Config.properties:/usr/local/tomcat/webapps/ROOT/Config.properties
    networks:
      app-network:
        ipv4_address: 192.168.2.174

volumes:
  mysql-data:

networks:
  app-network:
    ipam:
      config:
        - subnet: 192.168.2.0/24
